api_platform:
     #The title of the API.
    title: 'Sénégal Sites Historiques'

    #The description of the API.
    description: 'API : patrimoine historique du Sénégal'

    #The version of the API.
    version: '1.0.0'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
